//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebkaHaha.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessories()
        {
            this.ProductAccessories = new HashSet<ProductAccessories>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> IdAcessoriesImage { get; set; }
        public Nullable<int> IdTypeAccessories { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual AcessoriesImage AcessoriesImage { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TypeAccessories TypeAccessories { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAccessories> ProductAccessories { get; set; }
    }
}
