//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebkaHaha.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> IdMaterialImage { get; set; }
        public Nullable<int> IdTypeMaterial { get; set; }
        public Nullable<decimal> PriceOneKg { get; set; }
        public Nullable<int> IdStandart { get; set; }
        public Nullable<decimal> WidthMetr { get; set; }
        public Nullable<decimal> MassOneMetr { get; set; }
    
        public virtual MaterialImage MaterialImage { get; set; }
        public virtual Standart Standart { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
