//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebkaHaha.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationSpecification
    {
        public int IdProduct { get; set; }
        public string Operation { get; set; }
        public int Number { get; set; }
        public Nullable<int> IdTypeEquipment { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
    }
}
