//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebkaHaha.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAccessories
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public string AccessoriesArticle { get; set; }
        public decimal Count { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Product Product { get; set; }
    }
}
